Overnight in-arrears binary caplet
OpenGamma/Strata pull request #2443
Opened 2022-04-19 10:05 UTC by marc-henrard

* Trade model. 
* Pricer by call spread.

2022-05-04 10:02 UTC, skitini requested changes

2022-05-09 07:59 UTC, marc-henrard commented on modules/pricer/src/main/java/com/opengamma/strata/pricer/capfloor/VerticalSpreadSabrOvernightInArrerarCapletFloorletBinaryPeriodPricer.java
> +public class VerticalSpreadSabrOvernightInArrerarCapletFloorletBinaryPeriodPricer {
Corrected

2022-05-09 08:00 UTC, marc-henrard commented on modules/product/src/test/java/com/opengamma/strata/product/capfloor/OvernightInArrearsCapletFloorletBinaryPeriodTest.java
> +    CurrencyAmount payoffCalLongFixingLow = testCapLong.payoff(fixingLow);
Yes, correcte.

2022-05-09 08:03 UTC, marc-henrard commented on modules/pricer/src/test/java/com/opengamma/strata/pricer/capfloor/VerticalSpreadSabrOvernightInArrerarCapletFloorletBinaryPeriodPricerTest.java
> +  void present_value_deep_0tm() {
Corrected

2022-05-09 08:58 UTC, skitini approved these changes

2022-05-09 09:37 UTC, merged