Bond option pricing
OpenGamma/Strata pull request #2452
Opened 2022-05-09 09:40 UTC by marc-henrard

* Based on black formula and yield volatility. 
* Pricer: pv and sensitivities.
* Corrected a bug in bond forward price sensitivity

2022-05-11 17:05 UTC, yukiiwashita requested changes

2022-05-16 08:36 UTC, marc-henrard commented on modules/pricer/src/main/java/com/opengamma/strata/pricer/bond/DiscountingFixedCouponBondProductPricer.java
> +        double yieldBar = factor / couponPerYear /
Corrected. Added the missing relevant test.

2022-05-16 08:46 UTC, marc-henrard commented on modules/pricer/src/main/java/com/opengamma/strata/pricer/bond/DiscountingFixedCouponBondProductPricer.java
> +      double denBar = -2.0d * num * maturity / (den * den * den) / dirtyPrice;
Corrected. Added the missing relevant test.

2022-05-16 08:49 UTC, marc-henrard commented on modules/pricer/src/main/java/com/opengamma/strata/pricer/bond/NormalBondYieldExpiryDurationVolatilities.java
> +   * The y-value of the surface is the swap tenor, as a year fraction rounded to the month.
Done

2022-05-16 08:49 UTC, marc-henrard commented on modules/pricer/src/main/java/com/opengamma/strata/pricer/bond/BondVolatilitiesName.java
> + * The name of a set of swaption volatilities.
Done

2022-05-16 08:49 UTC, marc-henrard commented on modules/pricer/src/main/java/com/opengamma/strata/pricer/bond/BondYieldSensitivity.java
> +   * @param tenor  the underlying swap tenor
Done

2022-05-16 08:51 UTC, marc-henrard commented on modules/pricer/src/main/java/com/opengamma/strata/pricer/bond/DiscountingFixedCouponBondProductPricer.java
> +    double dfBar = -pv.getAmount() / (df * df) / notional * priceBar;
Yes needed. df is used in price computation. As priceBar=1, we could remove it, but I prefer to leave it  as it explain the code better to my point of view.

2022-05-16 09:33 UTC, yukiiwashita approved these changes

2022-05-16 09:33 UTC, merged