Create OvernightOvernightSwapConventions
OpenGamma/Strata pull request #2686
Opened 2024-12-05 13:30 UTC by brianweller89

Initially only needed for trade creation; hence `CurveNode` and `TradeTemplate` implementations have not been created

2024-12-05 15:43 UTC, jodastephen requested changes

2024-12-05 15:43 UTC, jodastephen commented on modules/product/src/main/java/com/opengamma/strata/product/swap/type/OvernightOvernightSwapConventions.java
> +      OvernightOvernightSwapConvention.of(StandardOvernightOvernightSwapConventions.USD_FED_FUND_SOFR_3M.getName());
The name `USD_FED_FUND_SOFR_3M` does not match `USD-SOFR-3M-FED-FUND-3M`. While painfully long, it is better to be consistent.

2024-12-05 15:55 UTC, jodastephen submitted a review, later dismissed

2024-12-19 10:42 UTC, marc-henrard approved these changes
Good for me

2024-12-19 10:42 UTC, merged